### ISSUE TITLE
fill out samples page

### ISSUE THREAD

**Issue by hanbollar** [KittyCAD/litterbox#1]
See https://github.com/KittyCAD/docs/issues/59 for previous commentary

Skip down to **[this comment](https://github.com/KittyCAD/litterbox/issues/1#issuecomment-1108938831)** for the latest proposal on the samples page.

---

More comments about ideas / design decisions / plan in the discussion below

Immediate tasks:
- [x] Polish current samples page with syntax highlighting and general polish.
- [x] Add more samples to litterbox
- [x] Investigate Editable and non editable sections in a code editor
- [ ] KittyCAD/docs#143

**Comment by Irev-Dev** [comment]
This is complete, there's some niggling things related to color, which has it's own issue.
https://github.com/KittyCAD/docs/issues/248
