### ISSUE TITLE
`output` on file conversions is deprecated

### ISSUE THREAD

**Issue by jessfraz** [KittyCAD/litterbox#132]
python and go are updated in #131 

javascript needs to be updated

**Comment by adamchalmers** [comment]
@pierremtb Are you able to take this on? The Javascript examples are on an old version of the library, but this issue is basically the same as https://github.com/KittyCAD/diff-viewer-extension/issues/370.

**Comment by pierremtb** [comment]
@adamchalmers oh yeah let me give it a go!

**Comment by adamchalmers** [comment]
Thank you!

**Comment by pierremtb** [comment]
![image](https://github.com/KittyCAD/litterbox/assets/10795683/3f256914-bc6a-40bd-b92d-4712eae0672b)

There's really only one place

**Comment by pierremtb** [comment]
![image](https://github.com/KittyCAD/litterbox/assets/10795683/9e957720-3687-4b27-9b5e-1d1448dc4491)

Alright looks like it worked

**Comment by pierremtb** [comment]
@adamchalmers I gotta say I'm not a huge fan of `outputs['source.stl']` in terms of intuitiveness. Maybe you have a good idea of a descriptive variable name for `'source.stl'`?

![image](https://github.com/KittyCAD/litterbox/assets/10795683/58e7a6e5-5fcb-4f79-98f1-8119fb023b3d)

**Comment by adamchalmers** [comment]
I agree, I just filed https://github.com/KittyCAD/api-deux/issues/1200 to fix that. Now you'll be able to choose the name of the file which gets returned. This will do for now, but once that issue is closed you can update this code if you want :)

**Comment by pierremtb** [comment]
Cool, done! Thanks for your input

I still see some inconsistencies between all three .py, .js, and .go, in terms of what things are above or below the `LITTERBOX-START-NON-EDITABLE-SECTION` waterline. Let me know if I should fix that too (maybe in a second PR)

![image](https://github.com/KittyCAD/litterbox/assets/10795683/0a54bef7-b188-4c5c-b54b-72c65ac739e0)
