### ISSUE TITLE
tutorial for mass endpoint for prod launch

### ISSUE THREAD

**Issue by hanbollar** [KittyCAD/litterbox#29]

**Comment by Irev-Dev** [comment]
@jessfraz, I think there might be an issue with the sdk for the mass and volume, either that or I'm not using it correctly.
I added `get_volume.py` and `get_mass.py` and functions for the new endpoints return very similar errors.
```
Error(error_code=<kittycad.types.Unset object at 0x7f4791aa6d90>, message='unable to parse query string: missing field `src_format`', request_id='96a9e6f1-bb24-4be0-827d-176251cde478', additional_properties={})
```
and 
```
Error(error_code=<kittycad.types.Unset object at 0x7fe68ec4beb0>, message='unable to parse query string: missing field `src_format`', request_id='073782d6-4c1e-42c8-95e5-03eb6181ae77', additional_properties={})
```
respectively.

Might the SDK not be adding the query param?

see #32.

**Comment by Irev-Dev** [comment]
Edit: looks like it's putting the format into the path not the query?
https://github.com/KittyCAD/kittycad.py/blob/main/kittycad/api/file/create_file_volume.py#L17

**Comment by jessfraz** [comment]
oh it very well could be! i can try and fix tomorrow

**Comment by jessfraz** [comment]
its likely somewhere around here: https://github.com/KittyCAD/kittycad.py/blob/main/generate/generate.py#L234

if you get to it before me

**Comment by jessfraz** [comment]
I fixed the go one

**Comment by Irev-Dev** [comment]
Ah thanks!
I've started looking at the python one, and I think I was wrong with my original guess about it being put into the path. Not sure where the problem is.

**Comment by jessfraz** [comment]
oh thats it tho! It needs a check for if its in the query or the path, essentially its trying to add it to the path but failing since there are no more vars!

**Comment by jessfraz** [comment]
this is a dumb diff i have so far but its not adding the query yet:

```
+    in_query = []
     if 'parameters' in endpoint:
         parameters = endpoint['parameters']
         for parameter in parameters:
@@ -246,12 +247,16 @@ response: Response[""" + success_type + """] = await """ + fn_name + """.asyncio
             else:
                 print("  parameter: ", parameter)
                 raise Exception("Unknown parameter type")
-            f.write(
-                ", " +
-                parameter_name +
-                "=" +
-                camel_to_snake(parameter_name))
+            if parameter['in'] == 'path'
+                f.write(
+                    ", " +
+                    parameter_name +
+                    "=" +
+                    camel_to_snake(parameter_name))
+            elif parameter['in'] == 'query'
+                in_query.push(parameter)
     f.write(")\n")
+    # Now we add the parameters to the query if there are any.
     f.write("\n")
     f.write("\theaders: Dict[str, Any] = client.get_headers()\n")
```

maybe that helps

also the makefile has some nice commands like make generate and make shell to pop you into a container w all the deps

**Comment by Irev-Dev** [comment]
Ah okay

Thanks for the makefile tip, mostly trying to grok the repo at this point.

This is mostly likely useful context for when I get around to making the JS SDK.

**Comment by jessfraz** [comment]
It’s one gigantic printf lolOn Jun 13, 2022, at 8:29 PM, Kurt Hutten ***@***.***> wrote:﻿
Ah okay
Thanks for the makefile tip, mostly trying to grok the repo at this point.
This is mostly likely useful context for when I get around to making the JS SDK.

**Comment by Irev-Dev** [comment]
Hot tip: don't create a virtual python environment in the python SDK repo and expect `make generate` to still work 🤦 

and yeah for sure, is this how code gen is normally done? tbh I was expecting AST related code, but I haven't every written openAPI code-gen, only used existing ones.

**Comment by jessfraz** [comment]
im sure the AST people are like WTF lol

**Comment by Irev-Dev** [comment]
Thank you!

And yeah fair enough. From memory the names for everything in AST land are not the most intuitive to say the least.
