### ISSUE TITLE
Release of interactive tutorial tool

### ISSUE THREAD

**Issue by hanbollar** [KittyCAD/litterbox#33]
The interactive tutorial is already live, it's only if there are tweaks we want before the release?

Otherwise there are some new tutorials we want before the release which may or may not use the litterbox
- https://github.com/KittyCAD/litterbox/issues/29
- https://github.com/KittyCAD/litterbox/issues/30

**Comment by JordanNoone** [comment]
@Irev-Dev @JBEmbedded Jenna had thoughts on pallet/color changes to match other website updates.

**Comment by Irev-Dev** [comment]
Pallet changes are covered by https://github.com/KittyCAD/docs/issues/248

Going to close this now, let me know if this is an error and there's something that needs to be done here.
